name: Tests

on:
  pull_request:
  push:
    # trying and staging branches are for BORS config
    branches:
      - trying
      - staging
      - main

jobs:
  linter_check:
    runs-on: ubuntu-latest
    name: linter-check
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dev dependencies
        run: yarn --dev
      - name: Run style check
        run: yarn lint && yarn prettier-check
  cypress_no_meilisearch:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ./node_modules
          key: ${{ hashFiles('yarn.lock') }}
      - name: Install dependencies
        run: yarn
      - name: Test no meilisearch running
        uses: cypress-io/github-action@v2
        with:
          start: yarn start:ci
          wait-on: 'http://0.0.0.0:3000'
          command: yarn cy:run:test-no-meilisearch
          config-file: cypress.json
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos
  cypress_meilisearch-no-api-key:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    services:
      meilisearch:
        image: getmeili/meilisearch:v0.27.0rc1
        env:
          MEILI_NO_ANALYTICS: 'true'
        ports:
          - '7700:7700'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ./node_modules
          key: ${{ hashFiles('yarn.lock') }}
      - name: Install dependencies
        run: yarn
      - name: Test
        uses: cypress-io/github-action@v2
        env:
          CYPRESS_host: http://meilisearch:7700
        with:
          start: yarn start:ci
          wait-on: 'http://0.0.0.0:3000'
          command: yarn cy:run
          config-file: cypress.json
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos
  cypress_meilisearch-api-key:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    services:
      meilisearch:
        image: getmeili/meilisearch:v0.27.0rc1
        env:
          MEILI_MASTER_KEY: 'masterKey'
          MEILI_NO_ANALYTICS: 'true'
        ports:
          - '7700:7700'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ./node_modules
          key: ${{ hashFiles('yarn.lock') }}
      - name: Install dependencies
        run: yarn
      - name: Test
        uses: cypress-io/github-action@v2
        env:
          CYPRESS_host: http://meilisearch:7700
        with:
          start: yarn start:ci
          wait-on: 'http://0.0.0.0:3000'
          command: yarn cy:run:test-api-key-required
          config-file: cypress.json
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos
